name: infineon_floodmonitoring
description: Infineon Flood Monitoring application, created by students from Singapore Polytechnic in partnership with Infineon Technologies Asia

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
#sdk: ">=2.1.0 <3.0.0"
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_messaging: ^5.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0
  liquid_pull_to_refresh: ^1.1.1
  #liquid_pull_to_refresh: ^1.1.0
  redux_thunk: ^0.2.1
  flip_box_bar: ^0.9.2
  #google_maps_flutter: ^0.5.15
  #google_maps_flutter: ^0.5.21+7
  google_maps_flutter: ^0.5.24+1
  #flutter_staggered_grid_view: "^0.2.7"
  flutter_staggered_grid_view: ^0.3.0
  charts_flutter: ^0.6.0
  http: ^0.12.0+2
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  #android: "launcher_icon"
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/error_images/error_dialog_icon.png
    - assets/error_images/logo.png
    - assets/intro_images/1.png
    - assets/intro_images/2.png
    - assets/intro_images/3.png
    - assets/about_images/1.jpg
    - assets/about_images/2.jpeg
    - assets/about_images/3.jpeg
    - assets/about_images/4.jpeg
    - assets/about_images/5.jpeg
    - assets/warning_images/warning.png
    - assets/logo/cityLogo.png
    - assets/logo/thermometer.png
    - assets/logo/gauge.png
    - assets/logo/speedometer.png
    - assets/backup_images/2.png
    - assets/dashboard_images/infineon.png
    - assets/dashboard_images/Singapore.jpg
    - assets/dashboard_images/Tampines.jpg
    - assets/dashboard_images/Yishun.jpg
    - assets/dashboard_images/Woodlands.jpg
    - assets/logo/clock.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
